import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { renderBlueprintViewer, safeJsonForHtml } from "../../src/viewer/render-html.js";
import { type BlueprintOutput } from "../../src/tools/compose/compose.types.js";

async function writePackageViewerFixture(packageRoot: string): Promise<void> {
  await mkdir(join(packageRoot, "dist", "viewer-assets", "assets"), { recursive: true });
  await writeFile(
    join(packageRoot, "dist", "viewer-assets", "index.html"),
    [
      "<!doctype html>",
      "<html>",
      "<head>",
      "<link rel=\"stylesheet\" crossorigin href=\"/assets/app.css\">",
      "</head>",
      "<body>",
      "<div id=\"root\"></div>",
      "<script type=\"module\" crossorigin src=\"/assets/app.js\"></script>",
      "</body>",
      "</html>",
    ].join(""),
    "utf-8",
  );
  await writeFile(join(packageRoot, "dist", "viewer-assets", "assets", "app.css"), ".app{color:red}", "utf-8");
  await writeFile(join(packageRoot, "dist", "viewer-assets", "assets", "app.js"), "console.log('viewer')", "utf-8");
}

async function writeBlueprintFixture(projectRoot: string): Promise<void> {
  await mkdir(join(projectRoot, ".blueprint", "groups"), { recursive: true });
  await writeFile(
    join(projectRoot, ".blueprint", "blueprint-output.json"),
    JSON.stringify(createBlueprintOutput(), null, 2),
    "utf-8",
  );
  await writeFile(
    join(projectRoot, ".blueprint", "groups", "runtime.md"),
    [
      "---",
      "id: group-runtime",
      "type: group-note",
      "groupId: runtime",
      "status: ready",
      "source: llm-authored",
      "---",
      "",
      "# Runtime",
      "",
      "## Snapshot",
      "Contains </script><script>alert('x')</script> text.",
      "",
    ].join("\n"),
    "utf-8",
  );
}

function createBlueprintOutput(): BlueprintOutput {
  return {
    schemaVersion: "blueprint.v1",
    project: {
      analysisArtifactId: "analysis_1",
      inventoryArtifactId: "inventory_1",
    },
    groups: [
      {
        id: "runtime",
        name: "Runtime",
        kind: "runtime",
        docsPath: ".blueprint/groups/runtime.md",
        fileIds: ["file_index"],
      },
    ],
    files: [
      {
        id: "file_index",
        path: "src/index.ts",
        groupId: "runtime",
        category: "source",
        language: "typescript",
        notesStatus: "not-required",
      },
    ],
    edges: [],
    fileEdges: [],
    symbols: [],
    entrypoints: [],
    testLinks: [],
    validation: {
      isValid: true,
      groupingComplete: true,
      groupingIssueSummary: [],
      groupingWarningSummary: [],
    },
  };
}

describe("renderBlueprintViewer", () => {
  it("writes a self-contained viewer HTML file into the user's hidden .blueprint directory", async () => {
    const projectRoot = await mkdtemp(join(tmpdir(), "blueprint-render-project-"));
    const packageRoot = await mkdtemp(join(tmpdir(), "blueprint-render-package-"));
    await writeBlueprintFixture(projectRoot);
    await writePackageViewerFixture(packageRoot);

    const result = await renderBlueprintViewer({ projectRoot, packageRoot });
    const html = await readFile(result.htmlPath, "utf-8");

    expect(result.htmlPath).toBe(join(projectRoot, ".blueprint", "index.html"));
    expect(html).toContain("generated by blueprint open - do not edit");
    expect(html).toContain("<style>.app{color:red}</style>");
    expect(html).toContain("<script type=\"module\">console.log('viewer')</script>");
    expect(html).toContain("<script id=\"blueprint-data\" type=\"application/json\">");
    expect(html).toContain("\\u003c/script>");
    expect(html).not.toContain("</script><script>alert");
  });
});

describe("safeJsonForHtml", () => {
  it("escapes script-breaking JSON characters", () => {
    expect(safeJsonForHtml({ value: "</script><!--\u2028\u2029-->" })).toBe(
      "{\"value\":\"\\u003c/script>\\u003c!--\\u2028\\u2029--\\u003e\"}",
    );
  });
});
