import { type CommitFileStatus } from "./commit-diff-reader.js";

export interface PostCommitChangedFileContext {
  status: CommitFileStatus;
  path: string;
  oldPath?: string;
  previousGroup?: string;
  currentGroup?: string;
  groupDocPath?: string;
}

export interface PostCommitPromptInput {
  commit: string;
  range: string;
  changedFiles: PostCommitChangedFileContext[];
  unassignedFiles: Array<{
    fileId: string;
    path: string;
    reason: string;
  }>;
  affectedGroupDocs: string[];
  affectedGroupDocContents: Array<{
    path: string;
    content: string;
  }>;
  projectLanguage: string;
  rawDiff: string;
}

export function buildPostCommitPrompt(input: PostCommitPromptInput): string {
  return [
    "# Blueprint Post-Commit Update",
    "",
    `Commit: ${input.commit}`,
    `Range: ${input.range}`,
    "",
    "## Changed Files",
    "",
    "| Status | Path | Previous Group | Current Group | Group Doc |",
    "|---|---|---|---|---|",
    ...input.changedFiles.map(formatChangedFileRow),
    "",
    "## Unassigned Files",
    "",
    "| File ID | Path | Reason |",
    "|---|---|---|",
    ...(input.unassignedFiles.length > 0
      ? input.unassignedFiles.map((file) =>
        `| ${escapeCell(file.fileId)} | ${escapeCell(file.path)} | ${escapeCell(file.reason)} |`)
      : ["| - | - | - |"]),
    "",
    "## Affected Group Docs",
    "",
    ...(input.affectedGroupDocs.length > 0
      ? input.affectedGroupDocs.map((path) => `- ${path}`)
      : ["- None"]),
    "",
    "## Affected Group Doc Contents",
    "",
    ...(input.affectedGroupDocContents.length > 0
      ? input.affectedGroupDocContents.flatMap((doc) => [
        `### ${doc.path}`,
        "",
        "```markdown",
        doc.content.trimEnd(),
        "```",
        "",
      ])
      : ["- None", ""]),
    "## Rules",
    "",
    `You must write JSON content and Markdown group docs in ${input.projectLanguage}.`,
    "Keep group markdown structure exactly as generated by compose.",
    "Do not translate frontmatter keys, the H1 title, HTML comments, or these section headings:",
    "Snapshot, Responsibilities, Core Flow, Contracts & Invariants, Key Files, Change Guide, Pitfalls, Tests, Debugging, Extension / Open Questions",
    "Only replace TODO body content under those existing headings with evidence-based content in the requested language.",
    "",
    "Allowed:",
    "- Use `blueprint.group.update` for grouping changes.",
    "- The affected group docs are already included in this prompt; use those contents before deciding.",
    "- Edit only the listed affected `blueprint/groups/*.md` files.",
    "- If `blueprint.group.update` creates a new group markdown file, keep the generated compose template intact and fill only its existing canonical sections.",
    "- Replace every TODO in any created or updated group markdown file with evidence-based content.",
    "- If new files are assigned to an existing group, you may edit that target group's markdown file.",
    "",
    "Forbidden:",
    "- Do not edit source files.",
    "- Do not edit `blueprint/blueprint-output.json` manually.",
    "- Do not run shell commands.",
    "- Do not update unrelated group docs.",
    "- Do not replace group doc frontmatter, the H1 title, or the canonical section headings.",
    "",
    "Required workflow:",
    "1. Review the changed files and raw diff.",
    "2. Assign every `__unassigned__` file using `blueprint.group.update`.",
    "3. After grouping updates, identify docs for groups that received files or changed behavior.",
    "4. Read each affected group doc before deciding.",
    "5. For each affected group doc, decide: `updated`, `reviewed-no-change`, or `needs-human-review`.",
    "6. Update docs only when responsibilities, flow, contracts, dependencies, key files, pitfalls, tests, or debugging guidance changed.",
    "7. Do not update docs for comments, formatting, local renames, or implementation-only noise.",
    "8. If unsure, do not invent. Mark `needs-human-review` and add a concise note.",
    "",
    "Final response format:",
    "- groupUpdate: called | not-needed",
    "- docsUpdated: [...]",
    "- docsReviewedNoChange: [...]",
    "- needsHumanReview: [...]",
    "- notes: [...]",
    "",
    "## Changed Areas",
    "",
    "```diff",
    input.rawDiff.trimEnd(),
    "```",
  ].join("\n");
}

function formatChangedFileRow(file: PostCommitChangedFileContext): string {
  const path = file.status === "renamed" && file.oldPath
    ? `${file.oldPath} -> ${file.path}`
    : file.path;
  return [
    "",
    file.status,
    escapeCell(path),
    escapeCell(file.previousGroup ?? "-"),
    escapeCell(file.currentGroup ?? "-"),
    escapeCell(file.groupDocPath ?? "-"),
    "",
  ].join(" | ");
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, "\\|");
}
