import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { viewerHtmlPath } from "../lib/blueprint-paths.js";
import { BlueprintViewerService } from "../services/blueprint-viewer-service.js";

export interface RenderBlueprintViewerOptions {
  projectRoot: string;
  packageRoot?: string;
  viewerService?: BlueprintViewerService;
}

export interface RenderBlueprintViewerResult {
  htmlPath: string;
}

export async function renderBlueprintViewer(
  options: RenderBlueprintViewerOptions,
): Promise<RenderBlueprintViewerResult> {
  const projectRoot = resolve(options.projectRoot);
  const packageRoot = options.packageRoot ? resolve(options.packageRoot) : defaultPackageRoot();
  const viewerService = options.viewerService ?? new BlueprintViewerService();
  const viewerData = await viewerService.viewerData(projectRoot);
  if (!viewerData.ok) {
    throw new Error(viewerData.message);
  }

  const html = await buildSelfContainedHtml(
    join(packageRoot, "dist", "viewer-assets"),
    safeJsonForHtml(viewerData.payload),
  );
  const htmlPath = viewerHtmlPath(projectRoot);
  await mkdir(dirname(htmlPath), { recursive: true });
  await writeFile(htmlPath, html, "utf-8");

  return { htmlPath };
}

export function safeJsonForHtml(value: unknown): string {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/-->/g, "--\\u003e")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

async function buildSelfContainedHtml(viewerRoot: string, embeddedJson: string): Promise<string> {
  const indexPath = join(viewerRoot, "index.html");
  let html = await readFile(indexPath, "utf-8");
  html = await inlineStyles(html, viewerRoot);
  html = await inlineScripts(html, viewerRoot);
  html = html.replace(
    "</head>",
    [
      "<script id=\"blueprint-data\" type=\"application/json\">",
      embeddedJson,
      "</script>",
      "</head>",
    ].join(""),
  );
  return [
    "<!-- generated by blueprint open - do not edit -->",
    html,
  ].join("\n");
}

async function inlineStyles(html: string, viewerRoot: string): Promise<string> {
  return await replaceAsync(
    html,
    /<link\s+rel="stylesheet"\s+crossorigin\s+href="([^"]+)">|<link\s+rel="stylesheet"\s+href="([^"]+)">/g,
    async (_match, crossoriginHref: string | undefined, href: string | undefined) => {
      const assetPath = assetPathFromHref(crossoriginHref ?? href ?? "");
      const css = await readFile(join(viewerRoot, assetPath), "utf-8");
      return `<style>${css}</style>`;
    },
  );
}

async function inlineScripts(html: string, viewerRoot: string): Promise<string> {
  return await replaceAsync(
    html,
    /<script\s+type="module"\s+crossorigin\s+src="([^"]+)"><\/script>|<script\s+type="module"\s+src="([^"]+)"><\/script>/g,
    async (_match, crossoriginSrc: string | undefined, src: string | undefined) => {
      const assetPath = assetPathFromHref(crossoriginSrc ?? src ?? "");
      const js = await readFile(join(viewerRoot, assetPath), "utf-8");
      return `<script type="module">${js}</script>`;
    },
  );
}

function assetPathFromHref(href: string): string {
  return href.replace(/^\//, "");
}

async function replaceAsync(
  input: string,
  pattern: RegExp,
  replace: (...args: string[]) => Promise<string>,
): Promise<string> {
  const matches = [...input.matchAll(pattern)];
  let output = input;
  for (const match of matches.reverse()) {
    const replacement = await replace(...match.map((value) => value ?? ""));
    output = `${output.slice(0, match.index)}${replacement}${output.slice((match.index ?? 0) + match[0].length)}`;
  }
  return output;
}

function defaultPackageRoot(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
}
